--
-- PostgreSQL database dump
--

\restrict aGrTILgpJhZYOTCk4uK23wnokKXlk1tf1vONVVLbhtO8VLNwNTB2rhkxmCpgYBF

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

-- Started on 2026-07-31 02:41:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16557)
-- Name: companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    address character varying(255),
    company_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    phone character varying(255),
    website character varying(255)
);


ALTER TABLE public.companies OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16556)
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16565)
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    address character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    customer_name character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(255),
    company_id bigint NOT NULL
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16564)
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16633)
-- Name: inventory_parts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory_parts (
    id bigint NOT NULL,
    category character varying(255),
    created_at timestamp(6) without time zone,
    minimum_stock integer,
    part_code character varying(255),
    part_name character varying(255),
    price numeric(38,2),
    quantity integer,
    unit character varying(255),
    company_id bigint,
    CONSTRAINT inventory_parts_category_check CHECK (((category)::text = ANY ((ARRAY['ELECTRICAL'::character varying, 'PLUMBING'::character varying, 'HVAC'::character varying, 'ELECTRONICS'::character varying, 'MECHANICAL'::character varying, 'SAFETY'::character varying, 'CLEANING'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.inventory_parts OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16632)
-- Name: inventory_parts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory_parts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_parts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16668)
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message text NOT NULL,
    read_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    technician_id bigint NOT NULL,
    CONSTRAINT notifications_status_check CHECK (((status)::text = ANY ((ARRAY['UNREAD'::character varying, 'READ'::character varying])::text[]))),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['WORK_ORDER_ASSIGNED'::character varying, 'WORK_ORDER_UPDATED'::character varying, 'WORK_ORDER_COMPLETED'::character varying, 'SLA_WARNING'::character varying, 'SLA_BREACHED'::character varying, 'GENERAL'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16667)
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16684)
-- Name: service_attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_attachments (
    id bigint NOT NULL,
    content_type character varying(255),
    file_name character varying(255),
    file_path character varying(255),
    file_size bigint,
    file_type character varying(255),
    file_url character varying(255),
    original_file_name character varying(255),
    uploaded_at timestamp(6) without time zone,
    service_report_id bigint NOT NULL,
    CONSTRAINT service_attachments_file_type_check CHECK (((file_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'PDF'::character varying, 'DOCUMENT'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.service_attachments OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16683)
-- Name: service_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16649)
-- Name: service_reports; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_reports (
    id bigint NOT NULL,
    customer_feedback character varying(500),
    hours_worked double precision,
    report_date timestamp(6) without time zone,
    status character varying(255),
    technician_notes character varying(1000),
    work_performed character varying(1000),
    technician_id bigint,
    work_order_id bigint,
    CONSTRAINT service_reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.service_reports OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16648)
-- Name: service_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16578)
-- Name: sites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sites (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    postal_code character varying(255),
    site_name character varying(255) NOT NULL,
    state character varying(255),
    customer_id bigint NOT NULL
);


ALTER TABLE public.sites OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16577)
-- Name: sites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16591)
-- Name: technicians; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.technicians (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    experience integer,
    full_name character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    specialization character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    company_id bigint NOT NULL,
    CONSTRAINT technicians_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BUSY'::character varying, 'OFFLINE'::character varying])::text[])))
);


ALTER TABLE public.technicians OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16590)
-- Name: technicians_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.technicians ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technicians_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16546)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'DISPATCHER'::character varying, 'TECHNICIAN'::character varying, 'CUSTOMER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16545)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16607)
-- Name: work_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.work_orders (
    id bigint NOT NULL,
    completed_date date,
    created_at timestamp(6) without time zone,
    description character varying(1000),
    priority character varying(255),
    scheduled_date date,
    status character varying(255),
    title character varying(255),
    customer_id bigint,
    site_id bigint,
    technician_id bigint,
    sla_due_date timestamp(6) without time zone,
    sla_status character varying(255),
    CONSTRAINT work_orders_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying, 'CRITICAL'::character varying])::text[]))),
    CONSTRAINT work_orders_sla_status_check CHECK (((sla_status)::text = ANY ((ARRAY['ON_TIME'::character varying, 'AT_RISK'::character varying, 'BREACHED'::character varying])::text[]))),
    CONSTRAINT work_orders_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.work_orders OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16606)
-- Name: work_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.work_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4802 (class 2606 OID 16563)
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 16571)
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- TOC entry 4814 (class 2606 OID 16640)
-- Name: inventory_parts inventory_parts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_parts
    ADD CONSTRAINT inventory_parts_pkey PRIMARY KEY (id);


--
-- TOC entry 4820 (class 2606 OID 16676)
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- TOC entry 4822 (class 2606 OID 16691)
-- Name: service_attachments service_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_attachments
    ADD CONSTRAINT service_attachments_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 16656)
-- Name: service_reports service_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_reports
    ADD CONSTRAINT service_reports_pkey PRIMARY KEY (id);


--
-- TOC entry 4806 (class 2606 OID 16584)
-- Name: sites sites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sites
    ADD CONSTRAINT sites_pkey PRIMARY KEY (id);


--
-- TOC entry 4808 (class 2606 OID 16598)
-- Name: technicians technicians_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.technicians
    ADD CONSTRAINT technicians_pkey PRIMARY KEY (id);


--
-- TOC entry 4810 (class 2606 OID 16600)
-- Name: technicians uk9miamdt1dkijdehwsr5kc4mgp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.technicians
    ADD CONSTRAINT uk9miamdt1dkijdehwsr5kc4mgp UNIQUE (email);


--
-- TOC entry 4816 (class 2606 OID 16642)
-- Name: inventory_parts ukel98yoekcur5u8r8nqle0f30y; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_parts
    ADD CONSTRAINT ukel98yoekcur5u8r8nqle0f30y UNIQUE (part_code);


--
-- TOC entry 4798 (class 2606 OID 16555)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4800 (class 2606 OID 16553)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4812 (class 2606 OID 16615)
-- Name: work_orders work_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT work_orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4826 (class 2606 OID 16626)
-- Name: work_orders fk3l21cwrh32e6em8pte8kfkixi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT fk3l21cwrh32e6em8pte8kfkixi FOREIGN KEY (technician_id) REFERENCES public.technicians(id);


--
-- TOC entry 4829 (class 2606 OID 16643)
-- Name: inventory_parts fk91vgi1k2tre6uv283p1wkh804; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory_parts
    ADD CONSTRAINT fk91vgi1k2tre6uv283p1wkh804 FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- TOC entry 4827 (class 2606 OID 16616)
-- Name: work_orders fk9bkpbdto93imqm7u6yg0r2kqw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT fk9bkpbdto93imqm7u6yg0r2kqw FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 4833 (class 2606 OID 16692)
-- Name: service_attachments fkaxupg092gr2ppss8julk58wiw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_attachments
    ADD CONSTRAINT fkaxupg092gr2ppss8julk58wiw FOREIGN KEY (service_report_id) REFERENCES public.service_reports(id);


--
-- TOC entry 4828 (class 2606 OID 16621)
-- Name: work_orders fkio9cg0efakk71fly5qtnw9m6h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_orders
    ADD CONSTRAINT fkio9cg0efakk71fly5qtnw9m6h FOREIGN KEY (site_id) REFERENCES public.sites(id);


--
-- TOC entry 4823 (class 2606 OID 16572)
-- Name: customers fkl9seru5curo311xhtpbxe3074; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fkl9seru5curo311xhtpbxe3074 FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- TOC entry 4824 (class 2606 OID 16585)
-- Name: sites fko4tggk9x1c2ulci91kvd43c3t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sites
    ADD CONSTRAINT fko4tggk9x1c2ulci91kvd43c3t FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- TOC entry 4825 (class 2606 OID 16601)
-- Name: technicians fko930arx7rwddvgyhl13r64iv6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.technicians
    ADD CONSTRAINT fko930arx7rwddvgyhl13r64iv6 FOREIGN KEY (company_id) REFERENCES public.companies(id);


--
-- TOC entry 4830 (class 2606 OID 16657)
-- Name: service_reports fkplbpt0lgthgphaf4l9nej0ejk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_reports
    ADD CONSTRAINT fkplbpt0lgthgphaf4l9nej0ejk FOREIGN KEY (technician_id) REFERENCES public.technicians(id);


--
-- TOC entry 4832 (class 2606 OID 16678)
-- Name: notifications fkqlmpa9fukshkp2q5tv7qwsedk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkqlmpa9fukshkp2q5tv7qwsedk FOREIGN KEY (technician_id) REFERENCES public.technicians(id);


--
-- TOC entry 4831 (class 2606 OID 16662)
-- Name: service_reports fksv9yng5b5n40lpwnl7w4vtdyf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_reports
    ADD CONSTRAINT fksv9yng5b5n40lpwnl7w4vtdyf FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id);


-- Completed on 2026-07-31 02:41:25

--
-- PostgreSQL database dump complete
--

\unrestrict aGrTILgpJhZYOTCk4uK23wnokKXlk1tf1vONVVLbhtO8VLNwNTB2rhkxmCpgYBF

